# Generated by Django 5.0.7 on 2024-08-27 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student_master',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('regd_no', models.AutoField(primary_key=True, serialize=False)),
                ('branch', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=5)),
                ('sec', models.CharField(max_length=5)),
                ('mob', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
